"""Tutor and Student different

Revision ID: 08486fef576c
Revises: 92d69fc098e4
Create Date: 2020-08-17 20:53:36.978817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08486fef576c'
down_revision = '92d69fc098e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=True))
        batch_op.drop_column('hash_password')

    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=True))
        batch_op.drop_column('hash_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_password', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('password')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_password', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
