"""columns added

Revision ID: 143889679711
Revises: 5c1d9015df27
Create Date: 2020-09-14 12:27:09.730363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143889679711'
down_revision = '5c1d9015df27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('awarded_by', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('awarded_date', sa.String(length=255), nullable=True))

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('travel_distance', sa.String(length=64), nullable=True))

    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('qualification_date', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.drop_column('qualification_date')
        batch_op.drop_column('institution')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('travel_distance')

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.drop_column('title')
        batch_op.drop_column('institution')

    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_column('awarded_date')
        batch_op.drop_column('awarded_by')

    # ### end Alembic commands ###
