"""achievement,experience,qualification tables created

Revision ID: 187725adf310
Revises: 9e470130a60b
Create Date: 2020-09-10 18:51:07.745736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187725adf310'
down_revision = '9e470130a60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('achievement', sa.String(length=255), nullable=True),
    sa.Column('achievement_file', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('experience', sa.String(length=255), nullable=True),
    sa.Column('experience_file', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('qualification_file', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=True))

    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('description')

    op.drop_table('qualification')
    op.drop_table('experience')
    op.drop_table('achievement')
    # ### end Alembic commands ###
