"""Tutor and Student different

Revision ID: 1ec9972036cc
Revises: ee9140129c04
Create Date: 2020-08-17 20:44:35.488034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec9972036cc'
down_revision = 'ee9140129c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('hash_password', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index('ix_student_email')
        batch_op.drop_index('ix_student_phone')
        batch_op.drop_index('ix_student_username')

    op.drop_table('student')
    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.drop_index('ix_tutor_email')
        batch_op.drop_index('ix_tutor_phone')
        batch_op.drop_index('ix_tutor_username')

    op.drop_table('tutor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('hash_password', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.create_index('ix_tutor_username', ['username'], unique=1)
        batch_op.create_index('ix_tutor_phone', ['phone'], unique=1)
        batch_op.create_index('ix_tutor_email', ['email'], unique=1)

    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('hash_password', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index('ix_student_username', ['username'], unique=1)
        batch_op.create_index('ix_student_phone', ['phone'], unique=1)
        batch_op.create_index('ix_student_email', ['email'], unique=1)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
