"""Tutor and Student different

Revision ID: 50210eccf932
Revises: a8b739afd4b2
Create Date: 2020-08-17 20:38:57.256507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50210eccf932'
down_revision = 'a8b739afd4b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_role')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=7), nullable=True))
        batch_op.create_index('ix_user_role', ['role'], unique=False)

    # ### end Alembic commands ###
