"""Course Table Added

Revision ID: 55d1af49b410
Revises: 0a99f65139bb
Create Date: 2020-09-01 18:02:35.494431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d1af49b410'
down_revision = '0a99f65139bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_title', sa.String(length=100), nullable=True),
    sa.Column('course_level', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    # ### end Alembic commands ###
