"""Tutor and Student different

Revision ID: 575e83ae4d43
Revises: 1ec9972036cc
Create Date: 2020-08-17 20:49:03.844898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575e83ae4d43'
down_revision = '1ec9972036cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('parent')

    # ### end Alembic commands ###
