"""travel distance removed

Revision ID: 5c1d9015df27
Revises: b3ef23223a24
Create Date: 2020-09-13 14:05:36.369292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1d9015df27'
down_revision = 'b3ef23223a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('travel_distance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('travel_distance', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
