"""account verification status aded to tutor

Revision ID: 84a821e76f5f
Revises: 8627a4a7c6d0
Create Date: 2020-09-19 11:00:04.048486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a821e76f5f'
down_revision = '8627a4a7c6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_verification_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.drop_column('account_verification_status')

    # ### end Alembic commands ###
