"""removed unique from role

Revision ID: a8b739afd4b2
Revises: 35d7821b5177
Create Date: 2020-08-15 20:28:59.157081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b739afd4b2'
down_revision = '35d7821b5177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_role')
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.create_index('ix_user_role', ['role'], unique=1)

    # ### end Alembic commands ###
