"""nullable fields

Revision ID: bba441000591
Revises: 55d1af49b410
Create Date: 2020-09-01 18:13:26.661432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba441000591'
down_revision = '55d1af49b410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('course_level',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('course_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('course_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('course_level',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
