"""nullable=false removed from time and cost

Revision ID: c0afaeaf2ecb
Revises: 187725adf310
Create Date: 2020-09-11 10:45:13.287687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0afaeaf2ecb'
down_revision = '187725adf310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mycourse', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.TIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mycourse', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.TIME(),
               nullable=False)
        batch_op.alter_column('cost',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
