"""dob added

Revision ID: eea873c10c80
Revises: df98a5b645a6
Create Date: 2020-09-02 10:45:17.319244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea873c10c80'
down_revision = 'df98a5b645a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_details', sa.String(length=255), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.drop_column('place_details')

    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.drop_column('place_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_details', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('date_of_birth')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_details', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('date_of_birth')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('place_details')

    # ### end Alembic commands ###
